add_newline = true

format = """
$directory$git_branch$git_status$python
$character
"""

[character]
success_symbol = "❯ "
error_symbol   = "✖ "
vicmd_symbol   = "❯ "

[directory]
format = "[$path]($style)"
style = "bold"
truncation_length = 3

[git_branch]
format = "[ |  ($branch) ]($style)"
style = "bold"

[git_status]
format = "[$all_status$ahead_behind]($style)"
style = "bold"

[python]
format = '[ |   ($virtualenv)]($style)'
style = "bold"
detect_env_vars = ["VIRTUAL_ENV"]
detect_extensions = []
detect_files = []
detect_folders = []

